/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ChatRouteRouteImport } from "./routes/chat/route"
import { Route as SettingsRouteRouteImport } from "./routes/settings/route"
import { Route as ChatIndexRouteImport } from "./routes/chat/index"
import { Route as ChatGraphRouteImport } from "./routes/chat/graph"
import { Route as ChatPinnedBranchesRouteImport } from "./routes/chat/pinned-branches"
import { Route as ChatSettingsRouteImport } from "./routes/chat/settings"
import { Route as SettingsIndexRouteImport } from "./routes/settings/index"
import { Route as SettingsAppearanceRouteImport } from "./routes/settings/appearance"
import { Route as SettingsSumiRouteImport } from "./routes/settings/sumi"
import { Route as SettingsToolsRouteImport } from "./routes/settings/tools"
import { Route as SettingsWebRouteImport } from "./routes/settings/web"
import { Route as SettingsWorkspaceIdIndexRouteImport } from "./routes/settings/$workspaceId/index"
import { Route as SettingsWorkspaceIdSettingRouteImport } from "./routes/settings/$workspaceId/$setting"
import { Route as SettingsProvidersProviderIdRouteImport } from "./routes/settings/providers/$providerId"
import { Route as SettingsProvidersNewRouteImport } from "./routes/settings/providers/new"
import { Route as SettingsWorkspacesNewRouteImport } from "./routes/settings/workspaces/new"
import { Route as SettingsProvidersNewIndexRouteImport } from "./routes/settings/providers/new/index"
import { Route as SettingsProvidersNewProviderIdRouteImport } from "./routes/settings/providers/new/$providerId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatGraphRoute = ChatGraphRouteImport.update({
  id: "/graph",
  path: "/graph",
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatPinnedBranchesRoute = ChatPinnedBranchesRouteImport.update({
  id: "/pinned-branches",
  path: "/pinned-branches",
  getParentRoute: () => ChatRouteRoute,
} as any)
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ChatRouteRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSumiRoute = SettingsSumiRouteImport.update({
  id: "/sumi",
  path: "/sumi",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsToolsRoute = SettingsToolsRouteImport.update({
  id: "/tools",
  path: "/tools",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWebRoute = SettingsWebRouteImport.update({
  id: "/web",
  path: "/web",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspaceIdIndexRoute =
  SettingsWorkspaceIdIndexRouteImport.update({
    id: "/$workspaceId/",
    path: "/$workspaceId/",
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsWorkspaceIdSettingRoute =
  SettingsWorkspaceIdSettingRouteImport.update({
    id: "/$workspaceId/$setting",
    path: "/$workspaceId/$setting",
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsProvidersProviderIdRoute =
  SettingsProvidersProviderIdRouteImport.update({
    id: "/providers/$providerId",
    path: "/providers/$providerId",
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsProvidersNewRoute = SettingsProvidersNewRouteImport.update({
  id: "/providers/new",
  path: "/providers/new",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsWorkspacesNewRoute = SettingsWorkspacesNewRouteImport.update({
  id: "/workspaces/new",
  path: "/workspaces/new",
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProvidersNewIndexRoute =
  SettingsProvidersNewIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => SettingsProvidersNewRoute,
  } as any)
const SettingsProvidersNewProviderIdRoute =
  SettingsProvidersNewProviderIdRouteImport.update({
    id: "/$providerId",
    path: "/$providerId",
    getParentRoute: () => SettingsProvidersNewRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/chat": typeof ChatRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/chat/graph": typeof ChatGraphRoute
  "/chat/pinned-branches": typeof ChatPinnedBranchesRoute
  "/chat/settings": typeof ChatSettingsRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/sumi": typeof SettingsSumiRoute
  "/settings/tools": typeof SettingsToolsRoute
  "/settings/web": typeof SettingsWebRoute
  "/chat/": typeof ChatIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/settings/$workspaceId/$setting": typeof SettingsWorkspaceIdSettingRoute
  "/settings/providers/$providerId": typeof SettingsProvidersProviderIdRoute
  "/settings/providers/new": typeof SettingsProvidersNewRouteWithChildren
  "/settings/workspaces/new": typeof SettingsWorkspacesNewRoute
  "/settings/$workspaceId/": typeof SettingsWorkspaceIdIndexRoute
  "/settings/providers/new/$providerId": typeof SettingsProvidersNewProviderIdRoute
  "/settings/providers/new/": typeof SettingsProvidersNewIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/chat/graph": typeof ChatGraphRoute
  "/chat/pinned-branches": typeof ChatPinnedBranchesRoute
  "/chat/settings": typeof ChatSettingsRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/sumi": typeof SettingsSumiRoute
  "/settings/tools": typeof SettingsToolsRoute
  "/settings/web": typeof SettingsWebRoute
  "/chat": typeof ChatIndexRoute
  "/settings": typeof SettingsIndexRoute
  "/settings/$workspaceId/$setting": typeof SettingsWorkspaceIdSettingRoute
  "/settings/providers/$providerId": typeof SettingsProvidersProviderIdRoute
  "/settings/workspaces/new": typeof SettingsWorkspacesNewRoute
  "/settings/$workspaceId": typeof SettingsWorkspaceIdIndexRoute
  "/settings/providers/new/$providerId": typeof SettingsProvidersNewProviderIdRoute
  "/settings/providers/new": typeof SettingsProvidersNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/chat": typeof ChatRouteRouteWithChildren
  "/settings": typeof SettingsRouteRouteWithChildren
  "/chat/graph": typeof ChatGraphRoute
  "/chat/pinned-branches": typeof ChatPinnedBranchesRoute
  "/chat/settings": typeof ChatSettingsRoute
  "/settings/appearance": typeof SettingsAppearanceRoute
  "/settings/sumi": typeof SettingsSumiRoute
  "/settings/tools": typeof SettingsToolsRoute
  "/settings/web": typeof SettingsWebRoute
  "/chat/": typeof ChatIndexRoute
  "/settings/": typeof SettingsIndexRoute
  "/settings/$workspaceId/$setting": typeof SettingsWorkspaceIdSettingRoute
  "/settings/providers/$providerId": typeof SettingsProvidersProviderIdRoute
  "/settings/providers/new": typeof SettingsProvidersNewRouteWithChildren
  "/settings/workspaces/new": typeof SettingsWorkspacesNewRoute
  "/settings/$workspaceId/": typeof SettingsWorkspaceIdIndexRoute
  "/settings/providers/new/$providerId": typeof SettingsProvidersNewProviderIdRoute
  "/settings/providers/new/": typeof SettingsProvidersNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/chat"
    | "/settings"
    | "/chat/graph"
    | "/chat/pinned-branches"
    | "/chat/settings"
    | "/settings/appearance"
    | "/settings/sumi"
    | "/settings/tools"
    | "/settings/web"
    | "/chat/"
    | "/settings/"
    | "/settings/$workspaceId/$setting"
    | "/settings/providers/$providerId"
    | "/settings/providers/new"
    | "/settings/workspaces/new"
    | "/settings/$workspaceId/"
    | "/settings/providers/new/$providerId"
    | "/settings/providers/new/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/chat/graph"
    | "/chat/pinned-branches"
    | "/chat/settings"
    | "/settings/appearance"
    | "/settings/sumi"
    | "/settings/tools"
    | "/settings/web"
    | "/chat"
    | "/settings"
    | "/settings/$workspaceId/$setting"
    | "/settings/providers/$providerId"
    | "/settings/workspaces/new"
    | "/settings/$workspaceId"
    | "/settings/providers/new/$providerId"
    | "/settings/providers/new"
  id:
    | "__root__"
    | "/"
    | "/chat"
    | "/settings"
    | "/chat/graph"
    | "/chat/pinned-branches"
    | "/chat/settings"
    | "/settings/appearance"
    | "/settings/sumi"
    | "/settings/tools"
    | "/settings/web"
    | "/chat/"
    | "/settings/"
    | "/settings/$workspaceId/$setting"
    | "/settings/providers/$providerId"
    | "/settings/providers/new"
    | "/settings/workspaces/new"
    | "/settings/$workspaceId/"
    | "/settings/providers/new/$providerId"
    | "/settings/providers/new/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/chat": {
      id: "/chat"
      path: "/chat"
      fullPath: "/chat"
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/chat/": {
      id: "/chat/"
      path: "/"
      fullPath: "/chat/"
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    "/chat/graph": {
      id: "/chat/graph"
      path: "/graph"
      fullPath: "/chat/graph"
      preLoaderRoute: typeof ChatGraphRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    "/chat/pinned-branches": {
      id: "/chat/pinned-branches"
      path: "/pinned-branches"
      fullPath: "/chat/pinned-branches"
      preLoaderRoute: typeof ChatPinnedBranchesRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    "/chat/settings": {
      id: "/chat/settings"
      path: "/settings"
      fullPath: "/chat/settings"
      preLoaderRoute: typeof ChatSettingsRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    "/settings/": {
      id: "/settings/"
      path: "/"
      fullPath: "/settings/"
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/appearance": {
      id: "/settings/appearance"
      path: "/appearance"
      fullPath: "/settings/appearance"
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/sumi": {
      id: "/settings/sumi"
      path: "/sumi"
      fullPath: "/settings/sumi"
      preLoaderRoute: typeof SettingsSumiRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/tools": {
      id: "/settings/tools"
      path: "/tools"
      fullPath: "/settings/tools"
      preLoaderRoute: typeof SettingsToolsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/web": {
      id: "/settings/web"
      path: "/web"
      fullPath: "/settings/web"
      preLoaderRoute: typeof SettingsWebRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/$workspaceId/": {
      id: "/settings/$workspaceId/"
      path: "/$workspaceId"
      fullPath: "/settings/$workspaceId/"
      preLoaderRoute: typeof SettingsWorkspaceIdIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/$workspaceId/$setting": {
      id: "/settings/$workspaceId/$setting"
      path: "/$workspaceId/$setting"
      fullPath: "/settings/$workspaceId/$setting"
      preLoaderRoute: typeof SettingsWorkspaceIdSettingRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/providers/$providerId": {
      id: "/settings/providers/$providerId"
      path: "/providers/$providerId"
      fullPath: "/settings/providers/$providerId"
      preLoaderRoute: typeof SettingsProvidersProviderIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/providers/new": {
      id: "/settings/providers/new"
      path: "/providers/new"
      fullPath: "/settings/providers/new"
      preLoaderRoute: typeof SettingsProvidersNewRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/workspaces/new": {
      id: "/settings/workspaces/new"
      path: "/workspaces/new"
      fullPath: "/settings/workspaces/new"
      preLoaderRoute: typeof SettingsWorkspacesNewRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    "/settings/providers/new/": {
      id: "/settings/providers/new/"
      path: "/"
      fullPath: "/settings/providers/new/"
      preLoaderRoute: typeof SettingsProvidersNewIndexRouteImport
      parentRoute: typeof SettingsProvidersNewRoute
    }
    "/settings/providers/new/$providerId": {
      id: "/settings/providers/new/$providerId"
      path: "/$providerId"
      fullPath: "/settings/providers/new/$providerId"
      preLoaderRoute: typeof SettingsProvidersNewProviderIdRouteImport
      parentRoute: typeof SettingsProvidersNewRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatGraphRoute: typeof ChatGraphRoute
  ChatPinnedBranchesRoute: typeof ChatPinnedBranchesRoute
  ChatSettingsRoute: typeof ChatSettingsRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatGraphRoute: ChatGraphRoute,
  ChatPinnedBranchesRoute: ChatPinnedBranchesRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface SettingsProvidersNewRouteChildren {
  SettingsProvidersNewProviderIdRoute: typeof SettingsProvidersNewProviderIdRoute
  SettingsProvidersNewIndexRoute: typeof SettingsProvidersNewIndexRoute
}

const SettingsProvidersNewRouteChildren: SettingsProvidersNewRouteChildren = {
  SettingsProvidersNewProviderIdRoute: SettingsProvidersNewProviderIdRoute,
  SettingsProvidersNewIndexRoute: SettingsProvidersNewIndexRoute,
}

const SettingsProvidersNewRouteWithChildren =
  SettingsProvidersNewRoute._addFileChildren(SettingsProvidersNewRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsSumiRoute: typeof SettingsSumiRoute
  SettingsToolsRoute: typeof SettingsToolsRoute
  SettingsWebRoute: typeof SettingsWebRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsWorkspaceIdSettingRoute: typeof SettingsWorkspaceIdSettingRoute
  SettingsProvidersProviderIdRoute: typeof SettingsProvidersProviderIdRoute
  SettingsProvidersNewRoute: typeof SettingsProvidersNewRouteWithChildren
  SettingsWorkspacesNewRoute: typeof SettingsWorkspacesNewRoute
  SettingsWorkspaceIdIndexRoute: typeof SettingsWorkspaceIdIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsSumiRoute: SettingsSumiRoute,
  SettingsToolsRoute: SettingsToolsRoute,
  SettingsWebRoute: SettingsWebRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsWorkspaceIdSettingRoute: SettingsWorkspaceIdSettingRoute,
  SettingsProvidersProviderIdRoute: SettingsProvidersProviderIdRoute,
  SettingsProvidersNewRoute: SettingsProvidersNewRouteWithChildren,
  SettingsWorkspacesNewRoute: SettingsWorkspacesNewRoute,
  SettingsWorkspaceIdIndexRoute: SettingsWorkspaceIdIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
